version: '3.5'

volumes:
  storage:
    driver: local

services:

  db:
    image: psql:local
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_DB=abacaba"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
#    volumes:
#      - type: volume
#        source: storage
#        target: /var/lib/postgresql/data